const fs=require('fs'),path=require('path'),assert=require('assert/strict'),crypto=require('crypto'),{performance}=require('perf_hooks');
const {load,root}=require('./context.cjs'),c=load(),{Tournament,Random,bonds}=c.AbstractChess,R=c.CHESS_ROSTER;
const byName=n=>{const h=R.find(x=>x.name===n);assert(h,n);return h;};
const piece=(name,star=2,uid=1)=>({id:byName(name).id,star,uid});
const timings=[],tests=[],problems=[];
function score(t,field){const fn=t.lineupScore||t.scoreLineup;assert.equal(typeof fn,'function','Expose Tournament.lineupScore(pieces) for objective verification');const v=fn.call(t,field);const n=typeof v==='number'?v:v.score;assert(Number.isFinite(n),'lineup score must be finite');return n;}
function put(p,units,level,seed=1){p.level=level;p.board=Array(24).fill(null);p.bench=Array(9).fill(null);const rng=new Random(seed),shuffled=rng.shuffle(units.map(u=>({...u}))),boardCount=Math.max(0,units.length-9);assert(boardCount<=level);const cells=rng.shuffle([...Array(24).keys()]);for(let i=0;i<boardCount;i++)p.board[cells[i]]=shuffled[i];for(let i=boardCount;i<shuffled.length;i++)p.bench[i-boardCount]=shuffled[i];}
const identity=u=>`${u.uid}:${u.id}:${u.star}`;
const identities=units=>Array.from(units,identity).sort();
const fieldKeys=(t,p)=>t.field(p).map(u=>u.uid).sort((a,b)=>a-b).join(',');
function greedy(t,owned,level){const strength=u=>(1+(c.CHESS_BY_ID.get(u.id).cost-1)*.32)*c.CHESS_RULES.stars[u.star-1],affinity=u=>{const hero=c.CHESS_BY_ID.get(u.id);return Math.min(.4,new Set(owned.filter(v=>v.id!==u.id&&c.CHESS_BY_ID.get(v.id).bonds.some(key=>hero.bonds.includes(key))).map(v=>v.id)).size*.1);};return [...owned].sort((a,b)=>(strength(b)+affinity(b))-(strength(a)+affinity(a))).slice(0,level);}
function maximum(t,units,level){let best=-Infinity,choices=[],evaluations=0;const k=Math.min(level,units.length);function visit(offset,chosen){if(chosen.length===k){const n=score(t,chosen);evaluations++;if(n>best+1e-9){best=n;choices=[chosen.map(u=>u.uid).sort((a,b)=>a-b).join(',')];}else if(Math.abs(n-best)<=1e-9)choices.push(chosen.map(u=>u.uid).sort((a,b)=>a-b).join(','));return;}for(let i=offset;i<=units.length-(k-chosen.length);i++)visit(i+1,[...chosen,units[i]]);}visit(0,[]);return{best,choices,evaluations};}
function check(name,units,level,{oracle=false,permutations=6}={}){const t=new Tournament(57811),p=t.player(),before=identities(units);let chosenKey=null,chosenScore=null;const sample={name,inventory:units.length,level,permutations};for(let order=1;order<=permutations;order++){put(p,units,level,order*7141);const start=performance.now();t.arrange(p);const elapsed=performance.now()-start;timings.push({name,ms:elapsed});assert.equal(p.board.length,24);assert.equal(p.bench.length,9);assert.deepEqual(identities(t.all(p)),before,name+' inventory conservation');assert.equal(t.field(p).length,Math.min(level,units.length));const key=fieldKeys(t,p),value=score(t,t.field(p));assert(value+1e-8>=score(t,greedy(t,units,level)),name+' selected score below old greedy');if(order===1){chosenKey=key;chosenScore=value;sample.chosen=t.field(p).map(u=>[c.CHESS_BY_ID.get(u.id).name,u.star]);sample.active=bonds(p.board).filter(b=>b.level).map(b=>b.key);}else assert.equal(key,chosenKey,name+' input permutation changes selected units');}
if(oracle){const max=maximum(t,units,level);assert(Math.abs(max.best-chosenScore)<=1e-8,name+' not maximum declared score');assert(max.choices.includes(chosenKey));sample.oracleEvaluations=max.evaluations;sample.score=chosenScore;}
// Unselected owned companions must not leak into a pure field-only score.
const chosen=t.field(p),originalScore=score(t,chosen);p.bench=R.slice(0,9).map((h,i)=>({id:h.id,uid:100+i,star:3}));assert.equal(score(t,chosen),originalScore,name+' bench leaks into field score');tests.push(sample);}
check('empty',[],3,{oracle:true});
check('fewer than cap',[piece('奶蛙',1,1),piece('汤圆',2,2)],3,{oracle:true});
check('猫素 duplicate alternatives',[piece('要乐奈',2,1),piece('要乐奈',2,2),piece('长崎素世',2,3),piece('椎名立希',2,4)],3,{oracle:true});
check('mother and cow breakpoint',[piece('牛妈妈',2,1),piece('牛妈妈',2,2),piece('牛来',2,3),piece('贝拉',2,4)],3,{oracle:true});
check('MyGO five breakpoint',['千早爱音','长崎素世','高松灯','要乐奈','椎名立希','椎名立希'].map((n,i)=>piece(n,2,i+1)),5,{oracle:true});
check('valuable upgraded duplicate',[piece('要乐奈',3,1),piece('要乐奈',2,2),piece('长崎素世',1,3),piece('袋鼠',1,4)],3,{oracle:true});
check('2992',['阿梓','嘉然','阿梓','七海','向晚'].map((n,i)=>piece(n,2,i+1)),3,{oracle:true});
for(let run=0;run<8;run++){const rng=new Random(31811+run*713),count=run===7?17:run<4?8:12,level=run===7?8:run<4?4:6,heroes=rng.shuffle(R).slice(0,count),units=heroes.map((h,i)=>({id:h.id,uid:i+1,star:1+Math.floor(rng.next()*3)}));if(run%2)units[count-1]={...units[0],star:1,uid:count};check('seeded inventory '+run,units,level,{oracle:run<4||run===7,permutations:run===7?3:6});}
const result={date:new Date().toISOString(),tests,timing:{calls:timings.length,meanMs:timings.reduce((s,x)=>s+x.ms,0)/timings.length,maxMs:Math.max(...timings.map(x=>x.ms)),full:timings.filter(x=>x.name==='seeded inventory 7')},hashes:Object.fromEntries(['chess-data.js','chess-engine.js'].map(f=>[f,crypto.createHash('sha256').update(fs.readFileSync(path.join(root,f))).digest('hex')])),limitations:'Declares best by the public lineup scoring function, not a mathematically guaranteed best team against every unknown future opponent. Node VM timing on this desktop is not mobile browser timing.'};console.log('Comprehensive arrangement passed:',tests.length,'inventories,',timings.length,'operations');
