const fs=require('fs'),path=require('path'),assert=require('assert/strict'),crypto=require('crypto');
const {load,root}=require('./context.cjs'),c=load(),{LineupEvaluator,lineupProfiles,Tournament,Random}=c.AbstractChess;
const names=[['千早爱音','长崎素世','高松灯','要乐奈','椎名立希','要乐奈','若叶睦','丰川祥子','八幡海铃','三角初华'],['阿梓','嘉然','七海','向晚','贝拉','珈乐','乃琳','阿梓','星瞳','明前奶绿'],['牛来','牛妈妈','贝拉','牛妈妈','奶蛙','奶龙','袋鼠','永雏塔菲','高松灯企鹅','张顺飞']];
for(let seed=1;seed<=3;seed++)names.push(new Random(seed*7763).shuffle(c.CHESS_ROSTER).slice(0,10).map(h=>h.name));
const shape=r=>({score:r.score,unique:r.unique,profiles:Array.from(r.profiles,p=>({uid:p.piece.uid,hp:p.hp,attack:p.attack,armor:p.armor,interval:p.interval,spell:p.spell,healing:p.healing,relations:p.relations,relationLead:p.relationLead,namedAura:p.namedAura,value:p.value})),active:Array.from(r.active,g=>[g.key,g.level])});
let compared=0;for(const [index,lineup]of names.entries()){const units=lineup.map((name,i)=>({uid:i+1,id:c.CHESS_ROSTER.find(h=>h.name===name).id,star:1+(i%3)})),model=new LineupEvaluator(units),masks=new Random(index*18271+71).shuffle([...Array(1<<units.length).keys()]);for(const mask of masks){const cached=shape(model.evaluate(mask,true)),subset=units.filter((u,i)=>mask&(1<<i)),fresh=shape(lineupProfiles(subset));assert.deepEqual(JSON.parse(JSON.stringify(cached)),JSON.parse(JSON.stringify(fresh)),'cache mismatch lineup '+index+' mask '+mask);compared++;}}
// Reusing a Tournament must invalidate selected lineup caching when a piece is
// upgraded/replaced/removed, or the player gains a field slot.
const t=new Tournament(215171),p=t.player();p.level=4;p.board=Array(24).fill(null);p.bench=names[0].slice(0,8).map((name,i)=>({uid:i+1,id:c.CHESS_ROSTER.find(h=>h.name===name).id,star:1+(i%2)}));p.bench.push(null);const mutations=[()=>{},()=>{t.all(p)[0].star=3;},()=>{t.all(p)[1].id=c.CHESS_ROSTER.find(h=>h.name==='阿梓').id;},()=>{p.level=5;},()=>{p.bench[p.bench.findIndex(Boolean)]=null;},()=>{const at=p.bench.indexOf(null);p.bench[at]={uid:91,id:c.CHESS_ROSTER.find(h=>h.name==='嘉然').id,star:2};}];
for(const mutate of mutations){mutate();const owned=t.all(p),expected=new LineupEvaluator(owned).best(p.level),result=t.arrange(p);assert(Math.abs(result.score-expected.score)<1e-9);assert.equal(t.field(p).map(u=>u.uid).sort((a,b)=>a-b).join(','),expected.chosen.map(u=>u.uid).sort((a,b)=>a-b).join(','));}
const result={date:new Date().toISOString(),cacheSubsetComparisons:compared,mutations:mutations.length,pass:true,hashes:Object.fromEntries(['chess-data.js','chess-engine.js'].map(f=>[f,crypto.createHash('sha256').update(fs.readFileSync(path.join(root,f))).digest('hex')]))};console.log('Cache equivalence passed:',compared,'subsets');
